FROM finance-agent-base:latest
# 安装 streamlit
RUN pip install --no-cache-dir streamlit pandas plotly deepeval

EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]